Repatch R-httpuv

diff --git a/bucket_31/R-httpuv/patches/patch-src_Makevars b/bucket_31/R-httpuv/patches/patch-src_Makevars
--- a/bucket_31/R-httpuv/patches/patch-src_Makevars
+++ b/bucket_31/R-httpuv/patches/patch-src_Makevars
@@ -1,4 +1,4 @@
---- src/Makevars.orig	2020-06-05 16:40:07 UTC
+--- src/Makevars.orig	2021-12-13 19:41:14 UTC
 +++ src/Makevars
 @@ -17,6 +17,9 @@ endif
  ifeq ($(UNAME), FreeBSD)
@@ -19,16 +19,15 @@
  # Fedora 28 defines _GLIBCXX_ASSERTIONS, so we better define it everywhere
  # to catch issues earlier.
  # jcheng 2018-06-18: Disabling _GLIBCXX_ASSERTIONS for now, as it causes
-@@ -64,9 +67,10 @@ libuv/m4/lt~obsolete.m4: libuv/m4/lt_obs
- # precisely the same timestamp value.
- libuv/Makefile: libuv/m4/lt~obsolete.m4
- 	(cd libuv \
--		&& touch aclocal.m4 \
--		&& touch -r aclocal.m4 configure Makefile.in \
- 		&& chmod +x configure \
-+		&& touch configure.ac \
-+		&& touch -r configure.ac Makefile.am aclocal.m4 *.in m4/* \
-+               && touch -r aclocal.m4 configure.ac configure \
- 		&& CC="$(CC)" CFLAGS="$(CFLAGS) $(CPICFLAGS) $(C_VISIBILITY)" AR="$(AR)" RANLIB="$(RANLIB)" LDFLAGS="$(LDFLAGS)" ./configure $(CONFIGURE_FLAGS))
- 
- libuv/.libs/libuv.a: libuv/Makefile
+@@ -74,8 +77,9 @@ libuv/Makefile: libuv/m4/lt~obsolete.m4
+ 	cd libuv; \
+ 	if ! command -v automake >/dev/null 2>&1 ; then \
+ 		echo "automake not found. Touching files so configure will not try to run automake."; \
+-		touch aclocal.m4; \
+-		touch -r aclocal.m4 configure Makefile.in; \
++		touch configure.ac; \
++		touch -r configure.ac Makefile.am aclocal.m4 *.in m4/*; \
++		touch -r aclocal.m4 configure.ac configure; \
+ 	else \
+ 		echo "automake found. Running autogen.sh."; \
+ 		sh autogen.sh; \
