complete rework on devcpu-data

diff --git a/bucket_CB/devcpu-data/files/microcode_update.in b/bucket_CB/devcpu-data/files/microcode_update.in
--- a/bucket_CB/devcpu-data/files/microcode_update.in
+++ b/bucket_CB/devcpu-data/files/microcode_update.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $FreeBSD: head/sysutils/devcpu-data/files/microcode_update.in 452203 2017-10-16 16:37:56Z riggs $
+# $FreeBSD: head/sysutils/devcpu-data/files/microcode_update.in 459084 2018-01-15 17:05:37Z swills $
 #
 
 # PROVIDE:	microcode_update
@@ -42,16 +42,31 @@ microcode_update_prepare()
 
 microcode_update_start()
 {
-	echo "Updating cpucodes..."
+	echo "Updating CPU Microcode..."
 	if [ "${microcode_cpus}" = "ALL" ]; then
 		ncpu=`/sbin/sysctl -n hw.ncpu`
 		cpus=`jot ${ncpu} 0`;
 	else
 		cpus=${microcode_cpus}
 	fi
+	for i in ${cpus}; do
 		${CMT} -u ${microcode_update_flags} \
-		    -d "${microcode_update_datadir}" /dev/cpuctl${i} || \
-		    (echo "Failed." && exit 1)
+                    -d "${microcode_update_datadir}" /dev/cpuctl${i} 2>&1 | \
+                    logger -p daemon.notice -t microcode_update || \
+		    (echo "Microcode Update Failed." && exit 1)
+	done
+	if [ "${microcode_cpus}" = "ALL" ]; then
+                CPUCONTROL_UPDATED=$(cpucontrol -h 2>&1 | grep -q -- -e; echo $?)
+                if [ ${CPUCONTROL_UPDATED} -ne 0 ]; then
+                        echo "Please update your system in order to update CPU microcode."
+                else
+			${CMT} -e /dev/cpuctl0 >/dev/null 2>&1
+			if [ $? -ne 0 ]; then
+				echo "Re-evalulation of CPU flags Failed."
+				exit 1
+			fi
+                fi
+	fi
 	echo "Done."
 }
 
