gnuplot: upgrade

diff --git a/bucket_F7/gnuplot/patches/patch-configure b/bucket_F7/gnuplot/patches/patch-configure
--- a/bucket_F7/gnuplot/patches/patch-configure
+++ b/bucket_F7/gnuplot/patches/patch-configure
@@ -1,38 +1,38 @@
---- configure.orig	2021-04-30 06:30:01 UTC
+--- configure.orig	2022-01-03 02:19:35 UTC
 +++ configure
-@@ -11421,12 +11421,12 @@ if test -n "$PKG_CONFIG"; then
+@@ -13041,12 +13041,12 @@ if test -n "$PKG_CONFIG"; then
          pkg_cv_LUA_CFLAGS="$LUA_CFLAGS"
      else
          if test -n "$PKG_CONFIG" && \
--    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua5.3\""; } >&5
+-    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua5.3\""; } >&5
 -  ($PKG_CONFIG --exists --print-errors "lua5.3") 2>&5
-+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua-5.3\""; } >&5
++    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua-5.3\""; } >&5
 +  ($PKG_CONFIG --exists --print-errors "lua-5.3") 2>&5
    ac_status=$?
-   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
    test $ac_status = 0; }; then
 -  pkg_cv_LUA_CFLAGS=`$PKG_CONFIG --cflags "lua5.3" 2>/dev/null`
 +  pkg_cv_LUA_CFLAGS=`$PKG_CONFIG --cflags "lua-5.3" 2>/dev/null`
  else
    pkg_failed=yes
  fi
-@@ -11439,12 +11439,12 @@ if test -n "$PKG_CONFIG"; then
+@@ -13059,12 +13059,12 @@ if test -n "$PKG_CONFIG"; then
          pkg_cv_LUA_LIBS="$LUA_LIBS"
      else
          if test -n "$PKG_CONFIG" && \
--    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua5.3\""; } >&5
+-    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua5.3\""; } >&5
 -  ($PKG_CONFIG --exists --print-errors "lua5.3") 2>&5
-+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua-5.3\""; } >&5
++    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua-5.3\""; } >&5
 +  ($PKG_CONFIG --exists --print-errors "lua-5.3") 2>&5
    ac_status=$?
-   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
    test $ac_status = 0; }; then
 -  pkg_cv_LUA_LIBS=`$PKG_CONFIG --libs "lua5.3" 2>/dev/null`
 +  pkg_cv_LUA_LIBS=`$PKG_CONFIG --libs "lua-5.3" 2>/dev/null`
  else
    pkg_failed=yes
  fi
-@@ -11463,9 +11463,9 @@ else
+@@ -13083,9 +13083,9 @@ else
          _pkg_short_errors_supported=no
  fi
          if test $_pkg_short_errors_supported = yes; then
@@ -44,48 +44,48 @@
          fi
  	# Put the nasty error message in config.log where it belongs
  	echo "$LUA_PKG_ERRORS" >&5
-@@ -11914,7 +11914,7 @@ else
+@@ -13534,7 +13534,7 @@ else
  	LUA_LIBS=$pkg_cv_LUA_LIBS
-         { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
- $as_echo "yes" >&6; }
+         { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+ printf "%s\n" "yes" >&6; }
 -	LUA=lua5.3
 +	LUA=lua53
  fi
  elif test $pkg_failed = untried; then
- 	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
-@@ -11929,12 +11929,12 @@ if test -n "$PKG_CONFIG"; then
+ 	{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+@@ -13549,12 +13549,12 @@ if test -n "$PKG_CONFIG"; then
          pkg_cv_LUA_CFLAGS="$LUA_CFLAGS"
      else
          if test -n "$PKG_CONFIG" && \
--    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua5.3\""; } >&5
+-    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua5.3\""; } >&5
 -  ($PKG_CONFIG --exists --print-errors "lua5.3") 2>&5
-+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua-5.3\""; } >&5
++    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua-5.3\""; } >&5
 +  ($PKG_CONFIG --exists --print-errors "lua-5.3") 2>&5
    ac_status=$?
-   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
    test $ac_status = 0; }; then
 -  pkg_cv_LUA_CFLAGS=`$PKG_CONFIG --cflags "lua5.3" 2>/dev/null`
-+  pkg_cv_LUA_CFLAGS=`$PKG_CONFIG --cflags "lua-5.3" 2>/dev/null`
++  pkg_cv_LUA_CFLAGS=`$PKG_CONFIG --cflags "lua- 5.3" 2>/dev/null`
  else
    pkg_failed=yes
  fi
-@@ -11947,12 +11947,12 @@ if test -n "$PKG_CONFIG"; then
+@@ -13567,12 +13567,12 @@ if test -n "$PKG_CONFIG"; then
          pkg_cv_LUA_LIBS="$LUA_LIBS"
      else
          if test -n "$PKG_CONFIG" && \
--    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua5.3\""; } >&5
+-    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua5.3\""; } >&5
 -  ($PKG_CONFIG --exists --print-errors "lua5.3") 2>&5
-+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua-5.3\""; } >&5
++    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"lua-5.3\""; } >&5
 +  ($PKG_CONFIG --exists --print-errors "lua-5.3") 2>&5
    ac_status=$?
-   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
    test $ac_status = 0; }; then
 -  pkg_cv_LUA_LIBS=`$PKG_CONFIG --libs "lua5.3" 2>/dev/null`
 +  pkg_cv_LUA_LIBS=`$PKG_CONFIG --libs "lua-5.3" 2>/dev/null`
  else
    pkg_failed=yes
  fi
-@@ -11971,9 +11971,9 @@ else
+@@ -13591,9 +13591,9 @@ else
          _pkg_short_errors_supported=no
  fi
          if test $_pkg_short_errors_supported = yes; then
@@ -97,21 +97,21 @@
          fi
  	# Put the nasty error message in config.log where it belongs
  	echo "$LUA_PKG_ERRORS" >&5
-@@ -12422,7 +12422,7 @@ else
+@@ -14042,7 +14042,7 @@ else
  	LUA_LIBS=$pkg_cv_LUA_LIBS
-         { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
- $as_echo "yes" >&6; }
+         { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+ printf "%s\n" "yes" >&6; }
 -	LUA=lua5.3
 +	LUA=lua53
  fi
  else
  	LUA_CFLAGS=$pkg_cv_LUA_CFLAGS
-@@ -12465,7 +12465,7 @@ return luaL_openlibs ();
+@@ -14083,7 +14083,7 @@ return luaL_openlibs ();
    return 0;
  }
  _ACEOF
--for ac_lib in '' lua lua5.3 lua5.2 lua5.1; do
-+for ac_lib in '' lua lua53 lua5.2 lua5.1; do
+-for ac_lib in '' lua lua5.3 lua5.2 lua5.1
++for ac_lib in '' lua lua53 lua5.2 lua5.1
+ do
    if test -z "$ac_lib"; then
      ac_res="none required"
-   else
