xmlto: fix build on sunos
While here, remove dependency on bash (taken from pkgsrc)

diff --git a/bucket_82/xmlto/patches/patch-xmlto.in b/bucket_82/xmlto/patches/patch-xmlto.in
--- a/bucket_82/xmlto/patches/patch-xmlto.in
+++ b/bucket_82/xmlto/patches/patch-xmlto.in
@@ -1,8 +1,39 @@
 This patch makes sure that w3m or others will not pollute $HOME/
 
---- ./xmlto.in.orig	2011-11-29 12:49:57.000000000 +0100
-+++ ./xmlto.in	2013-10-07 23:52:57.000000000 +0200
-@@ -611,4 +611,6 @@
+Avoid pointless bashisms.
+Avoid use of non POSIX local builtin.
+
+--- xmlto.in.orig	2015-11-16 14:07:10 UTC
++++ xmlto.in
+@@ -78,13 +78,15 @@ EOF
+ #  * Remembers the temporary file's name so it can be deleted on exit
+ #  * If the failure message is empty or missing, exits on failure
+ make_temp () {
+-  local dirflag="" prefix="@PACKAGE@"
++  dirflag="" prefix="@PACKAGE@"
+   [ "$1" = "-d" ] && { dirflag="-d"; shift; }
+   [ -n "$1" ] && prefix="@PACKAGE@-$1"
+ 
+-  if eval $2='$(${MKTEMP} $dirflag "${TMPDIR:-/tmp}/${prefix}.XXXXXX")'
++  tmpnam=$(${MKTEMP} $dirflag "${TMPDIR:-/tmp}/${prefix}.XXXXXX")
++  if [ $? = 0 ]
+   then
+-    CLEANFILES="$CLEANFILES ${!2}"
++    eval $2="$tmpnam"
++    CLEANFILES="$CLEANFILES $tmpnam"
+     return 0
+   elif [ -z "$3" ]
+   then
+@@ -97,7 +99,7 @@ make_temp () {
+ }
+ 
+ compute_searchpath () {
+-  local oldIFS="${IFS}"
++  oldIFS="${IFS}"
+   IFS=":"
+   for asearchpath in "$1"; do
+     # wrangle relative paths into absolute ones so that the user
+@@ -651,4 +653,6 @@ then
    # Extremely verbose
    BASH="${BASH} -x"
  fi
